In [1]:
import numpy as np

In [2]:
sequence_array = np.arange(10)
sequence_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
sequence_array.dtype

dtype('int64')

In [4]:
sequence_array.shape

(10,)

In [5]:
zero_array = np.zeros((3,2), dtype='int32')
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [6]:
zero_array.dtype

dtype('int32')

In [7]:
zero_array.shape

(3, 2)

In [8]:
one_array = np.ones((2, 3))

In [9]:
one_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
one_array.dtype

dtype('float64')

In [11]:
one_array.shape

(2, 3)

In [13]:
one_array.astype('int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [14]:
one_array.dtype

dtype('float64')