In [1]:
import numpy as np

In [2]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array2 = array1.reshape(2, 5)
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
array3 = array1.reshape(5, 2)
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [7]:
array1.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array1.reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
array1.reshape(5, -1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [10]:
array1.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

In [11]:
array1 = np.arange(8)

In [12]:
array3d = array1.reshape((2, 2, 2))

In [13]:
array3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
array5 = array3d.reshape(-1, 1)
array5

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [16]:
array1.reshape(-1, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])