In [1]:
import numpy as np

In [2]:
array1 = np.arange(start=1, stop=10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array1[2]

3

In [4]:
type(array1[2])

numpy.int64

In [5]:
array1[-1]

9

In [6]:
array1[-2]

8

In [7]:
array1[0]= 10
array1

array([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [8]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3, 3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2d[1, 1]

5

In [10]:
arr1 = np.arange(start=1, stop=10)
arr3 = arr1[0:3]
arr3

array([1, 2, 3])

In [11]:
type(arr3)

numpy.ndarray

In [12]:
arr1[:3]

array([1, 2, 3])

In [13]:
arr1[3:]

array([4, 5, 6, 7, 8, 9])

In [14]:
arr1[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr2d = arr1d.reshape(3, 3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2d[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [17]:
arr2d[1:3, :]

array([[4, 5, 6],
       [7, 8, 9]])

In [18]:
arr2d[0]

array([1, 2, 3])

In [19]:
arr2d[[0, 1], 2]

array([3, 6])

In [20]:
arr2d[[0, 1], 0:2]

array([[1, 2],
       [4, 5]])

In [21]:
arr2d[[0, 1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr1d[arr1d > 5]

array([6, 7, 8, 9])

In [24]:
arr1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])