In [8]:
import numpy as np

In [9]:
org = np.array([2, 5 ,1, 6, 9])
org

array([2, 5, 1, 6, 9])

In [11]:
sort1 = np.sort(org)
sort1

array([1, 2, 5, 6, 9])

In [12]:
org

array([2, 5, 1, 6, 9])

In [14]:
sort2 = org.sort()
type(sort2)

NoneType

In [15]:
org

array([1, 2, 5, 6, 9])

In [16]:
org[::-1]

array([9, 6, 5, 2, 1])

In [21]:
arr2d = np.array([[8,1, 3], [7,2,0]])
arr2d

array([[8, 1, 3],
       [7, 2, 0]])

In [22]:
sort3 = np.sort(arr2d, axis=0)
sort3

array([[7, 1, 0],
       [8, 2, 3]])

In [23]:
sort = np.sort(arr2d, axis=1)
sort

array([[1, 3, 8],
       [0, 2, 7]])

In [24]:
org = np.array([2, 5 ,1, 6, 9])
org

array([2, 5, 1, 6, 9])

In [25]:
sort = np.argsort(org)
sort

array([2, 0, 1, 3, 4])

In [27]:
type(sort)

numpy.ndarray

In [28]:
sort.tolist()

[2, 0, 1, 3, 4]

In [29]:
org[sort.tolist()]

array([1, 2, 5, 6, 9])

In [30]:
org

array([2, 5, 1, 6, 9])

In [31]:
sort = np.argsort(org)[::-1]
sort

array([4, 3, 1, 0, 2])

In [32]:
org[sort.tolist()]

array([9, 6, 5, 2, 1])

In [33]:
name = np.array(['J', 'M', 'S', 'K', 'Sa'])
score = np.array([78, 95, 84, 98, 88])

sort = np.argsort(score)
sort

array([0, 2, 4, 1, 3])

In [34]:
name[sort.tolist()]

array(['J', 'S', 'Sa', 'M', 'K'], dtype='<U2')