In [1]:
import numpy as np

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [6]:
B = np.array([[7,8], [9,10], [11,12]])
B.shape

(3, 2)

In [7]:
np.dot(A, B)

array([[ 58,  64],
       [139, 154]])

In [8]:
A @ B

array([[ 58,  64],
       [139, 154]])

In [9]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])