In [1]:
import numpy as np

dense = np.array([[3, 0, 1], [0, 2, 0]])
dense

array([[3, 0, 1],
       [0, 2, 0]])

In [2]:
from scipy import sparse

data = np.array([3, 1, 2])

row_pos = np.array([0, 0, 1])
col_pos = np.array([0, 2, 1])

sparse_coo = sparse.coo_matrix((data, (row_pos, col_pos)))
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

In [5]:
dense = np.array([[0, 0, 1, 0, 0, 5],
                 [1, 4, 0, 3, 2, 5],
                 [0, 6, 0, 3, 0, 0],
                 [2, 0, 0, 0, 0, 0],
                 [0, 0, 0, 7, 0, 8],
                 [1, 0, 0, 0, 0, 0]])

data = np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

rows = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
cols = np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

sparse_coo = sparse.coo_matrix((data, (rows, cols)))
print(sparse_coo.toarray())

rowx = np.array([0, 2, 7, 9, 10, 12, 13])



[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [6]:
sparse_csr = sparse.csr_matrix((data, cols, rowx))
print(sparse_csr.toarray())

[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [7]:
coo = sparse.coo_matrix(dense)
coo

<6x6 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in COOrdinate format>

In [8]:
coo.toarray()

array([[0, 0, 1, 0, 0, 5],
       [1, 4, 0, 3, 2, 5],
       [0, 6, 0, 3, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 8],
       [1, 0, 0, 0, 0, 0]])

In [9]:
csr = sparse.csr_matrix(dense)
csr

<6x6 sparse matrix of type '<class 'numpy.longlong'>'
	with 13 stored elements in Compressed Sparse Row format>